### ISSUE TITLE
renderer animation

### ISSUE THREAD

**Issue by GwennyGreen** [GwennyGreen/super-secret-led-wall#12]
I thought about how the renderers should be but I didn’t get it right until now.

The words should:

— **fade in**
— **only move upwards slowly** (different speeds are ok, different distances are ok)
— **fade out**

Since now I’ve decided on how the background animation looks, I think such a renderer could work fine with it. 

The negative phrases should have the **difference blend mode**.
The positive ones should have the **hard light blend mode**.

**Comment by claui** [comment]
Merged in #31.
