### ISSUE TITLE
Animate geometrical lines in html/css/js

### ISSUE THREAD

**Issue by GwennyGreen** [GwennyGreen/super-secret-led-wall#2]
- [ ] Choose random duration per animation

**Comment by claui** [comment]
@GwennyGreen Now that #9 is merged, I guess this issue can be closed.

**Comment by claui** [comment]
@GwennyGreen Disregard the last comment. I wasn’t aware we were talking about geometrical lines 🙈

**Comment by GwennyGreen** [comment]
I finished the animated lines for the background. They are called happy lines moving (for the positive side) and sad lines difference (for the negative side).
