### ISSUE TITLE
Lose outdated renderers

### ISSUE THREAD

**Issue by claui** [GwennyGreen/super-secret-led-wall#32]
@GwennyGreen Not sure if all our renderers still work as intended. Can we perhaps remove all the `crazy` renderers?

![crazyannarenderer](https://user-images.githubusercontent.com/1239874/48676279-baeab100-eb64-11e8-9481-a8b3ccb1c9bf.gif)

What about `ticking` and (the original) `slide_up`? Can we lose those, too?

**Comment by GwennyGreen** [comment]
Yes! All can go ecxept for the one we worked on yesterday (slide up anna?) We dan duplicate that one if we want to make others (eg. for font sizes).
